version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    #restart: always
    environment:
      POSTGRES_PASSWORD: prueba
    volumes:
      - postgresql:/var/lib/postgresql
volumes:
  postgresql:
